import Tree1 from '../../assets/Tree1.svg'
import Tree2 from '../../assets/Tree2.svg'
import Tree3 from '../../assets/Tree3.svg'
import Tree4 from '../../assets/Tree4.svg'
import Tree5 from '../../assets/Tree5.svg'
import Tree6 from '../../assets/Tree6.svg'
import Tree7 from '../../assets/Tree7.svg'
import Tree8 from '../../assets/Tree8.svg'
import Tree9 from '../../assets/Tree9.svg'

export { Tree1 }
export { Tree2 }
export { Tree3 }
export { Tree4 }
export { Tree5 }
export { Tree6 }
export { Tree7 }
export { Tree8 }
export { Tree9 }
